import enum


class FlaskBaseType(enum.Enum):
    Small      = "Small"
    Medium     = "Medium"
    Large      = "Large"
    Greater    = "Greater"
    Grand      = "Grand"
    Giant      = "Giant"
    Colossal   = "Colossal"
    Sacred     = "Sacred"
    Hallowed   = "Hallowed"
    Sanctified = "Sanctified"
    Divine     = "Divine"
    Eternal    = "Eternal"

    # utility flasks
    Quicksilver = "Quicksilver Flask"
    Bismuth     = "Bismuth Flask"
    Stibnite    = "Stibnite Flask"
    Amethyst    = "Amethyst Flask"
    Ruby        = "Ruby Flask"
    Sapphire    = "Sapphire Flask"
    Topaz       = "Topaz Flask"
    Silver      = "Silver Flask"
    Aquamarine  = "Aquamarine Flask"
    Granite     = "Granite Flask"
    Jade        = "Jade Flask"
    Quartz      = "Quartz Flask"
    Sulphur     = "Sulphur Flask"
    Basalt      = "Basalt Flask"
    Diamond     = "Diamond Flask"
    Gold        = "Gold Flask"
    Corundum    = "Corundum Flask"
    Iron        = "Iron Flask"
